# Daytona MultiQC dashboard configuration

title: "Daytona: SARS-CoV-2 NGS Analysis Report"
intro_text: >
  Interactive summary report (lineage and clade assignment, coverage QC, consensus assembly QC).

report_header_info:
  - Pipeline: "Daytona (https://github.com/BPHL-Molecular/Daytona)"
  - Version: "v1.0.0"
  - Contact: "bphl-sebioinformatics@flhealth.gov"
  - Laboratory: "Florida Bureau of Public Health Laboratories"

custom_css_files:
  - "daytona_report.css"

extra_fn_clean_exts:
  - "_raw"
  - "_clean"

max_table_rows: 1

skip_versions_section: true

exclude_modules:
  - "bbmap"
  - "kraken"
  - "samtools"
  - "trimmomatic"

module_order:
  - fastqc:
      name: "FastQC (raw reads)"
      anchor: "fastqc_raw"
      path_filters:
        - "*/fastqc/*"
  - fastqc:
      name: "FastQC (clean reads)"
      anchor: "fastqc_clean"
      path_filters:
        - "*/fastqc_clean/*"

remove_sections:
  - "fastqc_raw_fastqc_sequence_counts"
  - "fastqc_raw_fastqc_per_base_sequence_quality"
  - "fastqc_raw_fastqc_per_sequence_quality_scores"
  - "fastqc_raw_fastqc_raw_per_base_sequence_content"
  - "fastqc_raw_fastqc_per_sequence_gc_content"
  - "fastqc_raw_fastqc_per_base_n_content"
  - "fastqc_raw_fastqc_sequence_length_distribution"
  - "fastqc_raw_fastqc_sequence_duplication_levels"
  - "fastqc_raw_fastqc_overrepresented_sequences"
  - "fastqc_raw_fastqc_top_overrepresented_sequences"
  - "fastqc_raw_fastqc_adapter_content"
  - "fastqc_raw_fastqc_status_checks"
  - "fastqc_clean_fastqc_clean_per_base_sequence_content"
  - "fastqc_clean_fastqc_per_sequence_gc_content"
  - "fastqc_clean_fastqc_per_base_n_content"
  - "fastqc_clean_fastqc_sequence_length_distribution"
  - "fastqc_clean_fastqc_overrepresented_sequences"
  - "fastqc_clean_fastqc_top_overrepresented_sequences"

report_section_order:
  daytona_lineage:  { order: 4000 }
  daytona_assembly: { order: 3000 }
  fastqc_clean:     { order: 2000 }
  daytona_versions: { order: 1000 }

custom_content:
  order:
    - daytona_lineage
    - daytona_assembly
    - daytona_versions

table_columns_placement:
  "FastQC (raw reads)":
    total_sequences: 100
    median_sequence_length: 110
    percent_gc: 120
  "FastQC (clean reads)":
    total_sequences: 200
    median_sequence_length: 210
    percent_gc: 220

table_columns_visible:
  "FastQC (raw reads)":
    percent_duplicates: false
    median_sequence_length: true
  "FastQC (clean reads)":
    percent_duplicates: false
    median_sequence_length: true

table_cond_formatting_rules:
  qc_flag:
    pass:
      - s_eq: "PASS"
    fail:
      - s_contains: "FAIL"

  vadr_flag:
    pass:
      - s_eq: "PASS"
    warn:
      - s_eq: "REVIEW"
    fail:
      - s_contains: "FAIL"

  nextclade_clade:
    warn:
      - s_eq: "unassigned"
      - s_eq: "NA"

  lineage:
    warn:
      - s_eq: "Unassigned"
      - s_eq: "NA"
